function [PVI, PVD, VVIendo, VVDendo] = read_data()
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/maximo/Documents/MATLAB/IBM06/TP_7/datos_ventriculares.xls
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/07/17 23:30:10

%% Import the data
[~, ~, raw] = xlsread('/Users/maximo/Documents/MATLAB/IBM06/TP_7/datos_ventriculares.xls','Sheet1');
raw = raw(:,[2:3,7:8]);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
PVI = data(2:4401,1);
PVD = data(2:4401,2);
VVIendo = data(2:4401,3);
VVDendo = data(2:4401,4);

%% Clear temporary variables
clearvars data raw R;