function [Qao1, Pao1] = import_qao_and_pao()
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/maximo/Documents/MATLAB/IBM06/TP_FINAL/Datos_p_f_promedios.xls
%    Worksheet: Datos
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/08/16 18:15:05

%% Import the data
[~, ~, raw] = xlsread('/Users/maximo/Documents/MATLAB/IBM06/TP_FINAL/Datos_p_f_promedios.xls','Datos');
raw = raw(4:end,[3,6]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Pao1 = data(:,1);
Qao1 = data(:,2);

%% Clear temporary variables
clearvars data raw;